import Head from "next/head";
import Image from "next/image";
import Header from "@/components/Header/Header";
import Banner from "@/components/Banner/Banner";
import ProductNavigation from "@/components/Product_Navigation/ProductNavigation";
import Products from "@/components/Products/Products";
import Footer from "@/components/Footer/Footer";

import productsData from "@/components/ProductTile/data";

export default function Home() {
  return (
    <>
      <Head>
        <title>New Type Starfish Ocean</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header />
        <Banner />
        <ProductNavigation />
        <Products {...productsData} />
      </main>
      <Footer />
    </>
  );
}
